# This docker-compose script builds our program from scratch, and also
# runs the requisite redis image.
version: "3.5"

services:
  locator:
    build: ./locator
    ports:
      - '8080'
    environment:
      REDIS_URL: redis:6379
    depends_on:
      - redis

  analyzer:
    build: ./analyzer
    ports:
      - '8090'
    environment:
      REDIS_URL: redis:6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - '6379'
    logging:
      driver: none
